name: Android Feature CI Unit

on:
  push:
    branches:
      - '*'
      - 'master'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: change directory
        run: cd Booksies && ls && chmod +x ./gradlew

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Execute unit tests
      - name: Unit Test
        run: cd Booksies && ./gradlew test --stacktrace
    
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} 
