name: Build
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: cd Booksies && chmod +x ./gradlew && ./gradlew assembleDebug --stacktrace
